openapi: 3.0.0
info:
  title: TS test project
  description: API
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
paths:
  /auth/login:
    post:
      summary: Авторизация
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignIn'
      responses:
        '200':
          description: Токен авторизации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Неверная почта или пароль
        '500':
          description: Ошибка сервера

  /status:
    get:
      summary: Доступность сервера
      security: []
      responses:
        '200':
          description: Сервер доступен

  /currencies:
    get:
      summary: Список валют
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Список валют
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'
        '400':
          description: Неверные данные

    post:
      summary: Создание валюты
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCurrency'
      responses:
        '201':
          description: Валюта создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Currency'
        '400':
          description: Неверные данные

  /currencies/{id}:
    get:
      summary: Получение одной валюты
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Данные валюты
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Currency'
        '400':
          description: Неверные данные
        '404':
          description: Валюта не найдена

    put:
      summary: Обновление валюты
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCurrency'
      responses:
        '200':
          description: Валюта обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Currency'
        '400':
          description: Неверные данные
        '404':
          description: Валюта не найдена
    
    delete:
      summary: Удаление валюты
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Валюта удалена
        '400':
          description: Неверные данные
        '404':
          description: Валюта не найдена

  /price:
    get:
      summary: Получение цены валют по тикеру
      security:
        - bearerAuth: []
      parameters:
        - name: ticker
          in: query
          required: true
          schema:
           type: string
      responses:
        '200':
          description: Данные валют
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'
        '400':
          description: Тикер не указан
        '404':
          description: Нет данных по данному тикеру

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SignIn:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
        password:
          type: string
    
    AuthResponse:
      type: object
      properties:
        user:
          type: object
          properties:
            id:
              type: number
            email:
              type: string
        token:
          type: string

    Currency:
      type: object
      required: [id, name, ticker, price]
      properties:
        id:
          type: number
        name:
          type: string
        ticker:
          type: string
        price:
          type: number

    ExternalCurrency:
      type: object
      required: [symbol, price]
      properties:
        symbol:
          type: string
        price:
          type: string

    CreateCurrency:
      type: object
      required: [name, ticker, price]
      properties:
        name:
          type: string
        ticker:
          type: string
        price:
          type: number

    UpdateCurrency:
      type: object
      properties:
        name:
          type: string
        ticker:
          type: string
        price:
          type: number
