openapi: 3.0.0
info:
  title: TS test project
  description: API
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
paths:
  /auth/login:
    post:
      summary: Авторизация
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignIn'
      responses:
        '200':
          description: Токен авторизации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Неверная почта или пароль
        '500':
          description: Ошибка сервера

  /status:
    get:
      summary: Доступность сервера
      security: []
      responses:
        '200':
          description: Сервер доступен

  /currencies:
    get:
      summary: Список валют
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Список валют
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'
        '400':
          description: Неверные данные

    post:
      summary: Создание валюты
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCurrency'
      responses:
        '201':
          description: Валюта создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Currency'
        '400':
          description: Неверные данные
        '409':
          description: Валюта с таким тикером уже существует

  /currencies/{id}:
    get:
      summary: Получение одной валюты
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Данные валюты
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Currency'
        '400':
          description: Неверные данные
        '404':
          description: Валюта не найдена

    put:
      summary: Обновление валюты
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCurrency'
      responses:
        '200':
          description: Валюта обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Currency'
        '400':
          description: Неверные данные
        '404':
          description: Валюта не найдена

    delete:
      summary: Удаление валюты
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Валюта удалена
        '400':
          description: Неверные данные
        '404':
          description: Валюта не найдена

  /currencies/{id}/history:
    get:
      summary: Получение истории изменений цены валюты
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: История изменений цены валюты
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CurrencyHistory'
        '400':
          description: Неверные данные

  /price:
    get:
      summary: Получение цены валют по тикеру
      security:
        - bearerAuth: []
      parameters:
        - name: ticker
          in: query
          required: true
          schema:
           type: string
      responses:
        '200':
          description: Данные валют
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'
        '400':
          description: Тикер не указан
        '404':
          description: Нет данных по данному тикеру

  /wallets:
    get:
      summary: Список кошельков
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Список кошельков
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Wallet'
        '400':
          description: Неверные данные

    post:
      summary: Создание кошелька
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWallet'
      responses:
        '201':
          description: Кошелёк создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
        '400':
          description: Неверные данные
        '409':
          description: Кошелёк с таким адресом уже существует

  /wallets/{id}:
    put:
      summary: Обновление адреса кошелька
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWallet'
      responses:
        '200':
          description: Кошелёк обновлён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
        '400':
          description: Неверные данные
        '404':
          description: Кошелёк не найден

    delete:
      summary: Удаление кошелька
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Кошелёк удален
        '400':
          description: Неверные данные
        '404':
          description: Кошелёк не найден

  /wallets/{id}/buy:
    put:
      summary: Покупка валюты
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWalletBalance'
      responses:
        '200':
          description: Валюта куплена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletBalance'
        '400':
          description: Неверные данные


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SignIn:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
        password:
          type: string

    AuthResponse:
      type: object
      properties:
        user:
          type: object
          properties:
            id:
              type: number
            email:
              type: string
        token:
          type: string

    Currency:
      type: object
      required: [id, name, ticker, price]
      properties:
        id:
          type: number
        name:
          type: string
        ticker:
          type: string
        price:
          type: number

    CurrencyHistory:
      type: object
      required: [id, currencyId, price, timestamp]
      properties:
        id:
          type: number
        currencyId:
          type: number
        price:
          type: number
        timestamp:
          type: string

    Wallet:
      type: object
      required: [id, address]
      properties:
        id:
          type: number
        address:
          type: string

    WalletBalance:
      type: object
      required: [walletId, currencyId, amount]
      properties:
        walletId:
          type: number
        currencyId:
          type: number
        amount:
          type: number

    ExternalCurrency:
      type: object
      required: [symbol, price]
      properties:
        symbol:
          type: string
        price:
          type: string

    CreateCurrency:
      type: object
      required: [name, ticker, price]
      properties:
        name:
          type: string
        ticker:
          type: string
        price:
          type: number

    UpdateCurrency:
      type: object
      properties:
        name:
          type: string
        ticker:
          type: string
        price:
          type: number

    CreateWallet:
      type: object
      required: [address]
      properties:
        address:
          type: string

    UpdateWallet:
      type: object
      properties:
        address:
          type: string

    UpdateWalletBalance:
      type: object
      required: [currencyId, amount]
      properties:
        currencyId:
          type: number
        amount:
          type: number
